name: Pacman generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Needed for pushing

      - name: Create output directory
        run: mkdir -p dist

      - name: Install Pac-Man CLI
        run: npm install -g pacman-contribution-graph

      - name: Generate Pac-Man SVGs
        run: |
          # Light theme
          pacman-contribution-graph --platform github --gameTheme github --username kp-tech-19 > dist/pacman-contribution-graph.svg
          
          # Dark theme
          pacman-contribution-graph --platform github --gameTheme github-dark --username kp-tech-19 > dist/pacman-contribution-graph-dark.svg

      - name: List dist folder
        run: ls -la dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
