name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"   # run every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman Animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move output files
        run: |
          mkdir -p output
          mv pacman-contribution-graph.svg output/
          mv pacman-contribution-graph-dark.svg output/

      - name: Commit and Push to main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add output
          git commit -m "Update Pacman contribution graph" || echo "No changes"
          git push
